# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71ced3ad74f1258f2b4cca36e5b63024571b82551b42b7b2aed4be5edb3b2371050667fc015f9ef9f383d0a10514db83e56c1948deb503db3d663c5e46ef41d0

test:
  secret_key_base: 3ccb80b7c64dbb85e7650426eb9e0ce5bed48d5f42290f1f1986d0f8df38fd7485f4e87265b676bdf5cc67fbafd65fa4b42ff03f076cae8fe8a8ca0f30b61699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
